// Code generated by ent, DO NOT EDIT.

package attribute

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the attribute type in the database.
	Label = "attribute"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// EdgeMedia holds the string denoting the media edge name in mutations.
	EdgeMedia = "media"
	// EdgeMediaAttributes holds the string denoting the media_attributes edge name in mutations.
	EdgeMediaAttributes = "media_attributes"
	// Table holds the table name of the attribute in the database.
	Table = "attributes"
	// MediaTable is the table that holds the media relation/edge. The primary key declared below.
	MediaTable = "media_attributes"
	// MediaInverseTable is the table name for the Media entity.
	// It exists in this package in order to avoid circular dependency with the "media" package.
	MediaInverseTable = "media"
	// MediaAttributesTable is the table that holds the media_attributes relation/edge.
	MediaAttributesTable = "media_attributes"
	// MediaAttributesInverseTable is the table name for the MediaAttribute entity.
	// It exists in this package in order to avoid circular dependency with the "mediaattribute" package.
	MediaAttributesInverseTable = "media_attributes"
	// MediaAttributesColumn is the table column denoting the media_attributes relation/edge.
	MediaAttributesColumn = "attribute_id"
)

// Columns holds all SQL columns for attribute fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldType,
}

var (
	// MediaPrimaryKey and MediaColumn2 are the table columns denoting the
	// primary key for the media relation (M2M).
	MediaPrimaryKey = []string{"media_id", "attribute_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeTag     Type = "tag"
	TypeNumeric Type = "numeric"
	TypeDate    Type = "date"
	TypeString  Type = "string"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeTag, TypeNumeric, TypeDate, TypeString:
		return nil
	default:
		return fmt.Errorf("attribute: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Attribute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByMediaCount orders the results by media count.
func ByMediaCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMediaStep(), opts...)
	}
}

// ByMedia orders the results by media terms.
func ByMedia(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMediaStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMediaAttributesCount orders the results by media_attributes count.
func ByMediaAttributesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMediaAttributesStep(), opts...)
	}
}

// ByMediaAttributes orders the results by media_attributes terms.
func ByMediaAttributes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMediaAttributesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMediaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MediaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, MediaTable, MediaPrimaryKey...),
	)
}
func newMediaAttributesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MediaAttributesInverseTable, MediaAttributesColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, MediaAttributesTable, MediaAttributesColumn),
	)
}
