version: '3'

volumes:
  minio-data:
    driver: local
  bleve-index:
    driver: local
  postgres-data:
    driver: local
  model-cache:
    driver: local

services:
  caddy:
    image: caddy:2
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
    depends_on:
      - minio

  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  minio-init:
    image: minio/mc:latest
    depends_on: [minio]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
        set -e
        until mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do sleep 2; done
        mc mb --ignore-existing local/boorubucket
        mc anonymous set download local/boorubucket
        mc mb --ignore-existing local/previews
        mc anonymous set download local/previews
      "
  
  bleve-init:
    image: alpine:3.20
    volumes:
      - bleve-index:/data/bleve
    command: ["sh", "-c", "mkdir -p /data/bleve && chown -R 65532:65532 /data/bleve && chmod -R 755 /data/bleve"]
    user: root

  app:
    image: booru:prod
    build:
      context: .
      target: prod
    env_file:
      - .env
    environment:
      - POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    volumes:
      - bleve-index:/data/bleve
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      caddy:
        condition: service_started
      bleve-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8080:8080"
      
  media-worker:
    image: booru:media-worker
    build:
      context: .
      dockerfile: cmd/media_worker/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      app:
        condition: service_healthy

  image-embed-worker:
    image: booru:image-embed-worker
    build:
      context: .
      dockerfile: cmd/image_embed_worker/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      - MODEL_CACHE_DIR=/cache/models
    volumes:
      - model-cache:/cache
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      app:
        condition: service_healthy