// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"image", "video", "audio"}},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"user_tag", "meta_tag"}},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// MediaTagsColumns holds the columns for the "media_tags" table.
	MediaTagsColumns = []*schema.Column{
		{Name: "media_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// MediaTagsTable holds the schema information for the "media_tags" table.
	MediaTagsTable = &schema.Table{
		Name:       "media_tags",
		Columns:    MediaTagsColumns,
		PrimaryKey: []*schema.Column{MediaTagsColumns[0], MediaTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_tags_media_id",
				Columns:    []*schema.Column{MediaTagsColumns[0]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "media_tags_tag_id",
				Columns:    []*schema.Column{MediaTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MediaTable,
		TagsTable,
		MediaTagsTable,
	}
)

func init() {
	MediaTagsTable.ForeignKeys[0].RefTable = MediaTable
	MediaTagsTable.ForeignKeys[1].RefTable = TagsTable
}
