// Code generated by ent, DO NOT EDIT.

package ent

import (
	"era/booru/ent/attribute"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Attribute is the model entity for the Attribute schema.
type Attribute struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier for the attribute
	ID int `json:"id,omitempty"`
	// Name of the attribute
	Name string `json:"name,omitempty"`
	// Type of the attribute
	Type attribute.Type `json:"type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AttributeQuery when eager-loading is set.
	Edges        AttributeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AttributeEdges holds the relations/edges for other nodes in the graph.
type AttributeEdges struct {
	// Media holds the value of the media edge.
	Media []*Media `json:"media,omitempty"`
	// MediaAttributes holds the value of the media_attributes edge.
	MediaAttributes []*MediaAttribute `json:"media_attributes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MediaOrErr returns the Media value or an error if the edge
// was not loaded in eager-loading.
func (e AttributeEdges) MediaOrErr() ([]*Media, error) {
	if e.loadedTypes[0] {
		return e.Media, nil
	}
	return nil, &NotLoadedError{edge: "media"}
}

// MediaAttributesOrErr returns the MediaAttributes value or an error if the edge
// was not loaded in eager-loading.
func (e AttributeEdges) MediaAttributesOrErr() ([]*MediaAttribute, error) {
	if e.loadedTypes[1] {
		return e.MediaAttributes, nil
	}
	return nil, &NotLoadedError{edge: "media_attributes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Attribute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attribute.FieldID:
			values[i] = new(sql.NullInt64)
		case attribute.FieldName, attribute.FieldType:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Attribute fields.
func (a *Attribute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attribute.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case attribute.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case attribute.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				a.Type = attribute.Type(value.String)
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Attribute.
// This includes values selected through modifiers, order, etc.
func (a *Attribute) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// QueryMedia queries the "media" edge of the Attribute entity.
func (a *Attribute) QueryMedia() *MediaQuery {
	return NewAttributeClient(a.config).QueryMedia(a)
}

// QueryMediaAttributes queries the "media_attributes" edge of the Attribute entity.
func (a *Attribute) QueryMediaAttributes() *MediaAttributeQuery {
	return NewAttributeClient(a.config).QueryMediaAttributes(a)
}

// Update returns a builder for updating this Attribute.
// Note that you need to call Attribute.Unwrap() before calling this method if this Attribute
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Attribute) Update() *AttributeUpdateOne {
	return NewAttributeClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Attribute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Attribute) Unwrap() *Attribute {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Attribute is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Attribute) String() string {
	var builder strings.Builder
	builder.WriteString("Attribute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("name=")
	builder.WriteString(a.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", a.Type))
	builder.WriteByte(')')
	return builder.String()
}

// Attributes is a parsable slice of Attribute.
type Attributes []*Attribute
