// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"era/booru/ent/mediadate"
	"era/booru/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaDateDelete is the builder for deleting a MediaDate entity.
type MediaDateDelete struct {
	config
	hooks    []Hook
	mutation *MediaDateMutation
}

// Where appends a list predicates to the MediaDateDelete builder.
func (mdd *MediaDateDelete) Where(ps ...predicate.MediaDate) *MediaDateDelete {
	mdd.mutation.Where(ps...)
	return mdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mdd *MediaDateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mdd.sqlExec, mdd.mutation, mdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mdd *MediaDateDelete) ExecX(ctx context.Context) int {
	n, err := mdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mdd *MediaDateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mediadate.Table, sqlgraph.NewFieldSpec(mediadate.FieldID, field.TypeInt))
	if ps := mdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mdd.mutation.done = true
	return affected, err
}

// MediaDateDeleteOne is the builder for deleting a single MediaDate entity.
type MediaDateDeleteOne struct {
	mdd *MediaDateDelete
}

// Where appends a list predicates to the MediaDateDelete builder.
func (mddo *MediaDateDeleteOne) Where(ps ...predicate.MediaDate) *MediaDateDeleteOne {
	mddo.mdd.mutation.Where(ps...)
	return mddo
}

// Exec executes the deletion query.
func (mddo *MediaDateDeleteOne) Exec(ctx context.Context) error {
	n, err := mddo.mdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediadate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mddo *MediaDateDeleteOne) ExecX(ctx context.Context) {
	if err := mddo.Exec(ctx); err != nil {
		panic(err)
	}
}
