// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"era/booru/ent/mediaattribute"
	"era/booru/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// MediaAttributeDelete is the builder for deleting a MediaAttribute entity.
type MediaAttributeDelete struct {
	config
	hooks    []Hook
	mutation *MediaAttributeMutation
}

// Where appends a list predicates to the MediaAttributeDelete builder.
func (mad *MediaAttributeDelete) Where(ps ...predicate.MediaAttribute) *MediaAttributeDelete {
	mad.mutation.Where(ps...)
	return mad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mad *MediaAttributeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mad.sqlExec, mad.mutation, mad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mad *MediaAttributeDelete) ExecX(ctx context.Context) int {
	n, err := mad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mad *MediaAttributeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mediaattribute.Table, nil)
	if ps := mad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mad.mutation.done = true
	return affected, err
}

// MediaAttributeDeleteOne is the builder for deleting a single MediaAttribute entity.
type MediaAttributeDeleteOne struct {
	mad *MediaAttributeDelete
}

// Where appends a list predicates to the MediaAttributeDelete builder.
func (mado *MediaAttributeDeleteOne) Where(ps ...predicate.MediaAttribute) *MediaAttributeDeleteOne {
	mado.mad.mutation.Where(ps...)
	return mado
}

// Exec executes the deletion query.
func (mado *MediaAttributeDeleteOne) Exec(ctx context.Context) error {
	n, err := mado.mad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediaattribute.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mado *MediaAttributeDeleteOne) ExecX(ctx context.Context) {
	if err := mado.Exec(ctx); err != nil {
		panic(err)
	}
}
