// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"era/booru/ent/date"
	"era/booru/ent/media"
	"era/booru/ent/mediadate"
	"era/booru/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaDateQuery is the builder for querying MediaDate entities.
type MediaDateQuery struct {
	config
	ctx        *QueryContext
	order      []mediadate.OrderOption
	inters     []Interceptor
	predicates []predicate.MediaDate
	withMedia  *MediaQuery
	withDate   *DateQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MediaDateQuery builder.
func (mdq *MediaDateQuery) Where(ps ...predicate.MediaDate) *MediaDateQuery {
	mdq.predicates = append(mdq.predicates, ps...)
	return mdq
}

// Limit the number of records to be returned by this query.
func (mdq *MediaDateQuery) Limit(limit int) *MediaDateQuery {
	mdq.ctx.Limit = &limit
	return mdq
}

// Offset to start from.
func (mdq *MediaDateQuery) Offset(offset int) *MediaDateQuery {
	mdq.ctx.Offset = &offset
	return mdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mdq *MediaDateQuery) Unique(unique bool) *MediaDateQuery {
	mdq.ctx.Unique = &unique
	return mdq
}

// Order specifies how the records should be ordered.
func (mdq *MediaDateQuery) Order(o ...mediadate.OrderOption) *MediaDateQuery {
	mdq.order = append(mdq.order, o...)
	return mdq
}

// QueryMedia chains the current query on the "media" edge.
func (mdq *MediaDateQuery) QueryMedia() *MediaQuery {
	query := (&MediaClient{config: mdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mediadate.Table, mediadate.FieldID, selector),
			sqlgraph.To(media.Table, media.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, mediadate.MediaTable, mediadate.MediaColumn),
		)
		fromU = sqlgraph.SetNeighbors(mdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDate chains the current query on the "date" edge.
func (mdq *MediaDateQuery) QueryDate() *DateQuery {
	query := (&DateClient{config: mdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mediadate.Table, mediadate.FieldID, selector),
			sqlgraph.To(date.Table, date.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, mediadate.DateTable, mediadate.DateColumn),
		)
		fromU = sqlgraph.SetNeighbors(mdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MediaDate entity from the query.
// Returns a *NotFoundError when no MediaDate was found.
func (mdq *MediaDateQuery) First(ctx context.Context) (*MediaDate, error) {
	nodes, err := mdq.Limit(1).All(setContextOp(ctx, mdq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mediadate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mdq *MediaDateQuery) FirstX(ctx context.Context) *MediaDate {
	node, err := mdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MediaDate ID from the query.
// Returns a *NotFoundError when no MediaDate ID was found.
func (mdq *MediaDateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mdq.Limit(1).IDs(setContextOp(ctx, mdq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mediadate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mdq *MediaDateQuery) FirstIDX(ctx context.Context) int {
	id, err := mdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MediaDate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MediaDate entity is found.
// Returns a *NotFoundError when no MediaDate entities are found.
func (mdq *MediaDateQuery) Only(ctx context.Context) (*MediaDate, error) {
	nodes, err := mdq.Limit(2).All(setContextOp(ctx, mdq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mediadate.Label}
	default:
		return nil, &NotSingularError{mediadate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mdq *MediaDateQuery) OnlyX(ctx context.Context) *MediaDate {
	node, err := mdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MediaDate ID in the query.
// Returns a *NotSingularError when more than one MediaDate ID is found.
// Returns a *NotFoundError when no entities are found.
func (mdq *MediaDateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mdq.Limit(2).IDs(setContextOp(ctx, mdq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mediadate.Label}
	default:
		err = &NotSingularError{mediadate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mdq *MediaDateQuery) OnlyIDX(ctx context.Context) int {
	id, err := mdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MediaDates.
func (mdq *MediaDateQuery) All(ctx context.Context) ([]*MediaDate, error) {
	ctx = setContextOp(ctx, mdq.ctx, ent.OpQueryAll)
	if err := mdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MediaDate, *MediaDateQuery]()
	return withInterceptors[[]*MediaDate](ctx, mdq, qr, mdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mdq *MediaDateQuery) AllX(ctx context.Context) []*MediaDate {
	nodes, err := mdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MediaDate IDs.
func (mdq *MediaDateQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mdq.ctx.Unique == nil && mdq.path != nil {
		mdq.Unique(true)
	}
	ctx = setContextOp(ctx, mdq.ctx, ent.OpQueryIDs)
	if err = mdq.Select(mediadate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mdq *MediaDateQuery) IDsX(ctx context.Context) []int {
	ids, err := mdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mdq *MediaDateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mdq.ctx, ent.OpQueryCount)
	if err := mdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mdq, querierCount[*MediaDateQuery](), mdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mdq *MediaDateQuery) CountX(ctx context.Context) int {
	count, err := mdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mdq *MediaDateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mdq.ctx, ent.OpQueryExist)
	switch _, err := mdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mdq *MediaDateQuery) ExistX(ctx context.Context) bool {
	exist, err := mdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MediaDateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mdq *MediaDateQuery) Clone() *MediaDateQuery {
	if mdq == nil {
		return nil
	}
	return &MediaDateQuery{
		config:     mdq.config,
		ctx:        mdq.ctx.Clone(),
		order:      append([]mediadate.OrderOption{}, mdq.order...),
		inters:     append([]Interceptor{}, mdq.inters...),
		predicates: append([]predicate.MediaDate{}, mdq.predicates...),
		withMedia:  mdq.withMedia.Clone(),
		withDate:   mdq.withDate.Clone(),
		// clone intermediate query.
		sql:  mdq.sql.Clone(),
		path: mdq.path,
	}
}

// WithMedia tells the query-builder to eager-load the nodes that are connected to
// the "media" edge. The optional arguments are used to configure the query builder of the edge.
func (mdq *MediaDateQuery) WithMedia(opts ...func(*MediaQuery)) *MediaDateQuery {
	query := (&MediaClient{config: mdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mdq.withMedia = query
	return mdq
}

// WithDate tells the query-builder to eager-load the nodes that are connected to
// the "date" edge. The optional arguments are used to configure the query builder of the edge.
func (mdq *MediaDateQuery) WithDate(opts ...func(*DateQuery)) *MediaDateQuery {
	query := (&DateClient{config: mdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mdq.withDate = query
	return mdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MediaID string `json:"media_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MediaDate.Query().
//		GroupBy(mediadate.FieldMediaID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mdq *MediaDateQuery) GroupBy(field string, fields ...string) *MediaDateGroupBy {
	mdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MediaDateGroupBy{build: mdq}
	grbuild.flds = &mdq.ctx.Fields
	grbuild.label = mediadate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MediaID string `json:"media_id,omitempty"`
//	}
//
//	client.MediaDate.Query().
//		Select(mediadate.FieldMediaID).
//		Scan(ctx, &v)
func (mdq *MediaDateQuery) Select(fields ...string) *MediaDateSelect {
	mdq.ctx.Fields = append(mdq.ctx.Fields, fields...)
	sbuild := &MediaDateSelect{MediaDateQuery: mdq}
	sbuild.label = mediadate.Label
	sbuild.flds, sbuild.scan = &mdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MediaDateSelect configured with the given aggregations.
func (mdq *MediaDateQuery) Aggregate(fns ...AggregateFunc) *MediaDateSelect {
	return mdq.Select().Aggregate(fns...)
}

func (mdq *MediaDateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mdq); err != nil {
				return err
			}
		}
	}
	for _, f := range mdq.ctx.Fields {
		if !mediadate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mdq.path != nil {
		prev, err := mdq.path(ctx)
		if err != nil {
			return err
		}
		mdq.sql = prev
	}
	return nil
}

func (mdq *MediaDateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MediaDate, error) {
	var (
		nodes       = []*MediaDate{}
		_spec       = mdq.querySpec()
		loadedTypes = [2]bool{
			mdq.withMedia != nil,
			mdq.withDate != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MediaDate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MediaDate{config: mdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mdq.withMedia; query != nil {
		if err := mdq.loadMedia(ctx, query, nodes, nil,
			func(n *MediaDate, e *Media) { n.Edges.Media = e }); err != nil {
			return nil, err
		}
	}
	if query := mdq.withDate; query != nil {
		if err := mdq.loadDate(ctx, query, nodes, nil,
			func(n *MediaDate, e *Date) { n.Edges.Date = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mdq *MediaDateQuery) loadMedia(ctx context.Context, query *MediaQuery, nodes []*MediaDate, init func(*MediaDate), assign func(*MediaDate, *Media)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*MediaDate)
	for i := range nodes {
		fk := nodes[i].MediaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(media.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "media_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mdq *MediaDateQuery) loadDate(ctx context.Context, query *DateQuery, nodes []*MediaDate, init func(*MediaDate), assign func(*MediaDate, *Date)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MediaDate)
	for i := range nodes {
		fk := nodes[i].DateID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(date.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "date_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mdq *MediaDateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mdq.querySpec()
	_spec.Node.Columns = mdq.ctx.Fields
	if len(mdq.ctx.Fields) > 0 {
		_spec.Unique = mdq.ctx.Unique != nil && *mdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mdq.driver, _spec)
}

func (mdq *MediaDateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mediadate.Table, mediadate.Columns, sqlgraph.NewFieldSpec(mediadate.FieldID, field.TypeInt))
	_spec.From = mdq.sql
	if unique := mdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mdq.path != nil {
		_spec.Unique = true
	}
	if fields := mdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediadate.FieldID)
		for i := range fields {
			if fields[i] != mediadate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mdq.withMedia != nil {
			_spec.Node.AddColumnOnce(mediadate.FieldMediaID)
		}
		if mdq.withDate != nil {
			_spec.Node.AddColumnOnce(mediadate.FieldDateID)
		}
	}
	if ps := mdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mdq *MediaDateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mdq.driver.Dialect())
	t1 := builder.Table(mediadate.Table)
	columns := mdq.ctx.Fields
	if len(columns) == 0 {
		columns = mediadate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mdq.sql != nil {
		selector = mdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mdq.ctx.Unique != nil && *mdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mdq.predicates {
		p(selector)
	}
	for _, p := range mdq.order {
		p(selector)
	}
	if offset := mdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MediaDateGroupBy is the group-by builder for MediaDate entities.
type MediaDateGroupBy struct {
	selector
	build *MediaDateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mdgb *MediaDateGroupBy) Aggregate(fns ...AggregateFunc) *MediaDateGroupBy {
	mdgb.fns = append(mdgb.fns, fns...)
	return mdgb
}

// Scan applies the selector query and scans the result into the given value.
func (mdgb *MediaDateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mdgb.build.ctx, ent.OpQueryGroupBy)
	if err := mdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaDateQuery, *MediaDateGroupBy](ctx, mdgb.build, mdgb, mdgb.build.inters, v)
}

func (mdgb *MediaDateGroupBy) sqlScan(ctx context.Context, root *MediaDateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mdgb.fns))
	for _, fn := range mdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mdgb.flds)+len(mdgb.fns))
		for _, f := range *mdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MediaDateSelect is the builder for selecting fields of MediaDate entities.
type MediaDateSelect struct {
	*MediaDateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mds *MediaDateSelect) Aggregate(fns ...AggregateFunc) *MediaDateSelect {
	mds.fns = append(mds.fns, fns...)
	return mds
}

// Scan applies the selector query and scans the result into the given value.
func (mds *MediaDateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mds.ctx, ent.OpQuerySelect)
	if err := mds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaDateQuery, *MediaDateSelect](ctx, mds.MediaDateQuery, mds, mds.inters, v)
}

func (mds *MediaDateSelect) sqlScan(ctx context.Context, root *MediaDateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mds.fns))
	for _, fn := range mds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
