// Code generated by ent, DO NOT EDIT.

package mediadate

import (
	"era/booru/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldLTE(FieldID, id))
}

// MediaID applies equality check predicate on the "media_id" field. It's identical to MediaIDEQ.
func MediaID(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldEQ(FieldMediaID, v))
}

// DateID applies equality check predicate on the "date_id" field. It's identical to DateIDEQ.
func DateID(v int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldEQ(FieldDateID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v time.Time) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldEQ(FieldValue, v))
}

// MediaIDEQ applies the EQ predicate on the "media_id" field.
func MediaIDEQ(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldEQ(FieldMediaID, v))
}

// MediaIDNEQ applies the NEQ predicate on the "media_id" field.
func MediaIDNEQ(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldNEQ(FieldMediaID, v))
}

// MediaIDIn applies the In predicate on the "media_id" field.
func MediaIDIn(vs ...string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldIn(FieldMediaID, vs...))
}

// MediaIDNotIn applies the NotIn predicate on the "media_id" field.
func MediaIDNotIn(vs ...string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldNotIn(FieldMediaID, vs...))
}

// MediaIDGT applies the GT predicate on the "media_id" field.
func MediaIDGT(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldGT(FieldMediaID, v))
}

// MediaIDGTE applies the GTE predicate on the "media_id" field.
func MediaIDGTE(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldGTE(FieldMediaID, v))
}

// MediaIDLT applies the LT predicate on the "media_id" field.
func MediaIDLT(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldLT(FieldMediaID, v))
}

// MediaIDLTE applies the LTE predicate on the "media_id" field.
func MediaIDLTE(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldLTE(FieldMediaID, v))
}

// MediaIDContains applies the Contains predicate on the "media_id" field.
func MediaIDContains(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldContains(FieldMediaID, v))
}

// MediaIDHasPrefix applies the HasPrefix predicate on the "media_id" field.
func MediaIDHasPrefix(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldHasPrefix(FieldMediaID, v))
}

// MediaIDHasSuffix applies the HasSuffix predicate on the "media_id" field.
func MediaIDHasSuffix(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldHasSuffix(FieldMediaID, v))
}

// MediaIDEqualFold applies the EqualFold predicate on the "media_id" field.
func MediaIDEqualFold(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldEqualFold(FieldMediaID, v))
}

// MediaIDContainsFold applies the ContainsFold predicate on the "media_id" field.
func MediaIDContainsFold(v string) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldContainsFold(FieldMediaID, v))
}

// DateIDEQ applies the EQ predicate on the "date_id" field.
func DateIDEQ(v int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldEQ(FieldDateID, v))
}

// DateIDNEQ applies the NEQ predicate on the "date_id" field.
func DateIDNEQ(v int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldNEQ(FieldDateID, v))
}

// DateIDIn applies the In predicate on the "date_id" field.
func DateIDIn(vs ...int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldIn(FieldDateID, vs...))
}

// DateIDNotIn applies the NotIn predicate on the "date_id" field.
func DateIDNotIn(vs ...int) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldNotIn(FieldDateID, vs...))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v time.Time) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v time.Time) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...time.Time) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...time.Time) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v time.Time) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v time.Time) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v time.Time) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v time.Time) predicate.MediaDate {
	return predicate.MediaDate(sql.FieldLTE(FieldValue, v))
}

// HasMedia applies the HasEdge predicate on the "media" edge.
func HasMedia() predicate.MediaDate {
	return predicate.MediaDate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MediaTable, MediaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMediaWith applies the HasEdge predicate on the "media" edge with a given conditions (other predicates).
func HasMediaWith(preds ...predicate.Media) predicate.MediaDate {
	return predicate.MediaDate(func(s *sql.Selector) {
		step := newMediaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDate applies the HasEdge predicate on the "date" edge.
func HasDate() predicate.MediaDate {
	return predicate.MediaDate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, DateTable, DateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDateWith applies the HasEdge predicate on the "date" edge with a given conditions (other predicates).
func HasDateWith(preds ...predicate.Date) predicate.MediaDate {
	return predicate.MediaDate(func(s *sql.Selector) {
		step := newDateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaDate) predicate.MediaDate {
	return predicate.MediaDate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaDate) predicate.MediaDate {
	return predicate.MediaDate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaDate) predicate.MediaDate {
	return predicate.MediaDate(sql.NotPredicates(p))
}
