// Code generated by ent, DO NOT EDIT.

package vector

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the vector type in the database.
	Label = "vector"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeMedia holds the string denoting the media edge name in mutations.
	EdgeMedia = "media"
	// EdgeMediaVectors holds the string denoting the media_vectors edge name in mutations.
	EdgeMediaVectors = "media_vectors"
	// Table holds the table name of the vector in the database.
	Table = "vectors"
	// MediaTable is the table that holds the media relation/edge. The primary key declared below.
	MediaTable = "media_vectors"
	// MediaInverseTable is the table name for the Media entity.
	// It exists in this package in order to avoid circular dependency with the "media" package.
	MediaInverseTable = "media"
	// MediaVectorsTable is the table that holds the media_vectors relation/edge.
	MediaVectorsTable = "media_vectors"
	// MediaVectorsInverseTable is the table name for the MediaVector entity.
	// It exists in this package in order to avoid circular dependency with the "mediavector" package.
	MediaVectorsInverseTable = "media_vectors"
	// MediaVectorsColumn is the table column denoting the media_vectors relation/edge.
	MediaVectorsColumn = "vector_id"
)

// Columns holds all SQL columns for vector fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// MediaPrimaryKey and MediaColumn2 are the table columns denoting the
	// primary key for the media relation (M2M).
	MediaPrimaryKey = []string{"media_id", "vector_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Vector queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByMediaCount orders the results by media count.
func ByMediaCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMediaStep(), opts...)
	}
}

// ByMedia orders the results by media terms.
func ByMedia(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMediaStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMediaVectorsCount orders the results by media_vectors count.
func ByMediaVectorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMediaVectorsStep(), opts...)
	}
}

// ByMediaVectors orders the results by media_vectors terms.
func ByMediaVectors(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMediaVectorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMediaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MediaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, MediaTable, MediaPrimaryKey...),
	)
}
func newMediaVectorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MediaVectorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, MediaVectorsTable, MediaVectorsColumn),
	)
}
