// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MediaTag struct {
	MediaID int64 `json:"media_id"`
	TagID   int32 `json:"tag_id"`
}

type Medium struct {
	ID        int64              `json:"id"`
	Hash      []byte             `json:"hash"`
	MimeType  string             `json:"mime_type"`
	Width     int32              `json:"width"`
	Height    int32              `json:"height"`
	Duration  pgtype.Float4      `json:"duration"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
