// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Date is the predicate function for date builders.
type Date func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// MediaDate is the predicate function for mediadate builders.
type MediaDate func(*sql.Selector)

// MediaVector is the predicate function for mediavector builders.
type MediaVector func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Vector is the predicate function for vector builders.
type Vector func(*sql.Selector)
