// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attribute is the predicate function for attribute builders.
type Attribute func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// MediaAttribute is the predicate function for mediaattribute builders.
type MediaAttribute func(*sql.Selector)
